import React from 'react';
import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
const api=vi.hoisted(()=>({sendVerify:vi.fn(),verifyRegister:vi.fn(),upgradeGuest:vi.fn(),login:vi.fn(),sendCode:vi.fn(),forgotPassword:vi.fn(),resetPassword:vi.fn(),consent:vi.fn()}));
vi.mock('../services/apiService',()=>({authApi:api}));
vi.mock('../services/referral',()=>({clearStoredRef:vi.fn(),isChannelRef:()=>false,getStoredRef:()=>null}));
import { AuthModal } from './AuthModal';
import { GuestUpgradeModal } from './GuestUpgradeModal';
import { ResetPasswordModal } from './ResetPasswordModal';
import { KakaoConsentSheet } from './KakaoConsentSheet';
import { formatCountdown } from './RegistrationForm';
import { GuestAuthHeader } from './GuestAuthHeader';
const yes={terms:true,privacy:true,age14:true};const user={id:1,role:'USER',paidPoints:0,bonusPoints:1000,personaXp:{}};
beforeEach(()=>{vi.clearAllMocks();localStorage.clear();api.sendVerify.mockResolvedValue({});api.verifyRegister.mockResolvedValue({user,token:'mock-token'});api.upgradeGuest.mockResolvedValue({user,token:'mock-token'});api.login.mockResolvedValue({user,token:'mock-token'});api.resetPassword.mockResolvedValue({});api.consent.mockResolvedValue({recorded:true});});
afterEach(()=>{cleanup();vi.useRealTimers()});
function fillRegistration(upgrade=false){fireEvent.change(screen.getByLabelText('닉네임'),{target:{value:'tester'}});fireEvent.change(screen.getByLabelText(upgrade?'이메일':'휴대전화번호'),{target:{value:upgrade?'person@example.test':'01012345678'}});fireEvent.change(screen.getByLabelText('비밀번호',{selector:'input'}),{target:{value:'abcdef'}});}
describe('separate auth screens and affirmative consent',()=>{
 it('login has single purpose and opposite signup link, no tabs',()=>{render(<AuthModal onSuccess={vi.fn()} />);expect(screen.getByRole('heading',{name:'로그인'})).toBeTruthy();expect(screen.getByRole('button',{name:'로그인하기'})).toBeTruthy();expect(screen.getByText('처음 오셨나요?')).toBeTruthy();expect(screen.queryByRole('tab')).toBeNull();fireEvent.click(screen.getByRole('button',{name:'회원가입하기'}));expect(screen.getByRole('heading',{name:'회원가입'})).toBeTruthy();expect(screen.queryByRole('button',{name:'로그인하기',exact:true})).toBeTruthy();});
 it('register default phone, missing individual consent blocks sending',()=>{render(<AuthModal defaultMode="register" onSuccess={vi.fn()} />);fillRegistration();const next=screen.getByRole('button',{name:'인증번호 받기'}) as HTMLButtonElement;expect(next.disabled).toBe(true);fireEvent.click(next);expect(api.sendVerify).not.toHaveBeenCalled();fireEvent.click(screen.getByLabelText('필수 항목에 모두 동의'));expect(next.disabled).toBe(false);fireEvent.click(screen.getByLabelText('[필수] 만 14세 이상'));expect(next.disabled).toBe(true);});
 it('terms and collection details preserve input/check state',async()=>{render(<AuthModal defaultMode="register" onSuccess={vi.fn()} />);fillRegistration();fireEvent.click(screen.getByLabelText('필수 항목에 모두 동의'));fireEvent.click(screen.getByRole('button',{name:'이용약관 보기'}));expect(screen.getByText(/AI 놀이터 서비스/)).toBeTruthy();fireEvent.click(screen.getByRole('button',{name:'닫기'}));expect((screen.getByLabelText('닉네임') as HTMLInputElement).value).toBe('tester');expect((screen.getByLabelText('필수 항목에 모두 동의') as HTMLInputElement).checked).toBe(true);fireEvent.click(screen.getByRole('button',{name:'개인정보 수집·이용 보기'}));fireEvent.click(screen.getByRole('button',{name:'내용 확인하고 돌아가기'}));expect((screen.getByRole('button',{name:'인증번호 받기'}) as HTMLButtonElement).disabled).toBe(false);expect(api.sendVerify).not.toHaveBeenCalled();});
 it('phone registration sends normalized contact and affirmed payload only at verified completion',async()=>{const success=vi.fn();render(<AuthModal defaultMode="register" onSuccess={success} />);fillRegistration();fireEvent.click(screen.getByLabelText('필수 항목에 모두 동의'));fireEvent.click(screen.getByRole('button',{name:'인증번호 받기'}));await screen.findByText('2/2 인증 확인');expect(api.sendVerify).toHaveBeenCalledWith('PHONE','01012345678');expect(screen.getByText('다시 받기까지 01:00')).toBeTruthy();expect((screen.getByRole('button',{name:'인증번호 다시 받기'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.change(screen.getByLabelText('인증번호 (6자리)'),{target:{value:'123456'}});fireEvent.click(screen.getByRole('button',{name:'회원가입 완료하기'}));await waitFor(()=>expect(api.verifyRegister).toHaveBeenCalledWith('PHONE','01012345678','123456','abcdef','tester',yes));expect(success).toHaveBeenCalledWith(user,'mock-token',true);});
 it('back to signup retains information and consent without extra stages',async()=>{render(<AuthModal defaultMode="register" onSuccess={vi.fn()} />);fillRegistration();fireEvent.click(screen.getByLabelText('필수 항목에 모두 동의'));fireEvent.click(screen.getByRole('button',{name:'인증번호 받기'}));await screen.findByText('2/2 인증 확인');fireEvent.click(screen.getByRole('button',{name:/가입 정보 수정/}));expect((screen.getByLabelText('닉네임') as HTMLInputElement).value).toBe('tester');expect((screen.getByLabelText('필수 항목에 모두 동의') as HTMLInputElement).checked).toBe(true);});
 it('single email-switch button replaces contact field, no second tab group',()=>{render(<AuthModal defaultMode="register" onSuccess={vi.fn()} />);fireEvent.click(screen.getByRole('button',{name:'이메일로 가입하기'}));expect(screen.getByLabelText('이메일')).toBeTruthy();expect(screen.queryByLabelText('휴대전화번호')).toBeNull();expect(screen.queryByRole('tab')).toBeNull();});
 it('login password visibility and normalized identifier retain existing contract',async()=>{const success=vi.fn();render(<AuthModal onSuccess={success} />);fireEvent.change(screen.getByLabelText('이메일 또는 휴대전화번호'),{target:{value:'010-1234-5678'}});fireEvent.change(screen.getByLabelText('비밀번호',{selector:'input'}),{target:{value:'abcdef'}});fireEvent.click(screen.getByRole('button',{name:'비밀번호 보기'}));expect((screen.getByLabelText('비밀번호',{selector:'input'}) as HTMLInputElement).type).toBe('text');fireEvent.click(screen.getByRole('button',{name:'로그인하기'}));await waitFor(()=>expect(api.login).toHaveBeenCalledWith('01012345678','abcdef'));expect(success).toHaveBeenCalled();});
 it('forgot switches phone code vs email link CTA and has quiet Kakao text',async()=>{render(<AuthModal onSuccess={vi.fn()} />);fireEvent.click(screen.getByRole('button',{name:'비밀번호 찾기'}));expect(screen.getByRole('button',{name:'재설정 링크 받기'})).toBeTruthy();fireEvent.change(screen.getByLabelText('이메일 또는 휴대전화번호'),{target:{value:'010-1234-5678'}});fireEvent.click(screen.getByRole('button',{name:'인증번호 받기'}));await waitFor(()=>expect(api.sendCode).toHaveBeenCalledWith('01012345678'));expect(screen.getByLabelText('인증번호 (6자리)')).toBeTruthy();});
});
describe('upgrade, reset, header and Kakao',()=>{
 it('upgrade keeps body portal and email default with consent payload',async()=>{const success=vi.fn();const {container}=render(<GuestUpgradeModal onSuccess={success} onClose={vi.fn()} />);expect(container.childElementCount).toBe(0);expect(document.querySelector('.z-\\[9000\\]')).toBeTruthy();expect(screen.getByText('지금까지의 대화와 남은 포인트를 유지해요.')).toBeTruthy();fillRegistration(true);fireEvent.click(screen.getByLabelText('필수 항목에 모두 동의'));fireEvent.click(screen.getByRole('button',{name:'인증번호 받기'}));await screen.findByText('2/2 인증 확인');fireEvent.change(screen.getByLabelText('인증번호 (6자리)'),{target:{value:'123456'}});fireEvent.click(screen.getByRole('button',{name:'정식가입 완료하기'}));await waitFor(()=>expect(api.upgradeGuest).toHaveBeenCalledWith('EMAIL','person@example.test','123456','abcdef','tester',yes));});
 it('reset waits for explicit login return and does not auto-close',async()=>{const close=vi.fn();render(<ResetPasswordModal token="local-token" onClose={close} />);fireEvent.change(screen.getByLabelText('새 비밀번호',{selector:'input'}),{target:{value:'abcdef'}});fireEvent.change(screen.getByLabelText('새 비밀번호 확인',{selector:'input'}),{target:{value:'abcdef'}});fireEvent.click(screen.getByRole('button',{name:'비밀번호 변경하기'}));await screen.findByRole('button',{name:'로그인으로 돌아가기'});expect(close).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'로그인으로 돌아가기'}));expect(close).toHaveBeenCalledOnce();});
 it('header has distinct callbacks',()=>{const login=vi.fn(),register=vi.fn();render(<GuestAuthHeader onLogin={login} onRegister={register} onMenu={vi.fn()} />);fireEvent.click(screen.getByRole('button',{name:'회원가입'}));expect(register).toHaveBeenCalledOnce();expect(login).not.toHaveBeenCalled();fireEvent.click(screen.getByRole('button',{name:'로그인'}));expect(login).toHaveBeenCalledOnce();});
 it('countdown formats rollover',()=>{expect([60,59,1,0].map(formatCountdown)).toEqual(['01:00','00:59','00:01','00:00']);});
 it('Kakao requires actual save success; failure retains checks and allows retry',async()=>{const success=vi.fn();api.consent.mockRejectedValueOnce(new Error('storage unavailable'));render(<KakaoConsentSheet onConfirmed={success} onLogout={vi.fn()} />);expect((screen.getByRole('button',{name:'동의하고 시작하기'}) as HTMLButtonElement).disabled).toBe(true);fireEvent.click(screen.getByLabelText('필수 항목에 모두 동의'));fireEvent.click(screen.getByRole('button',{name:'동의하고 시작하기'}));expect(await screen.findByRole('alert')).toHaveProperty('textContent','storage unavailable');expect(success).not.toHaveBeenCalled();expect((screen.getByLabelText('필수 항목에 모두 동의') as HTMLInputElement).checked).toBe(true);fireEvent.click(screen.getByRole('button',{name:'동의하고 시작하기'}));await waitFor(()=>expect(success).toHaveBeenCalledOnce());expect(api.consent).toHaveBeenCalledWith(yes);});
});
