import React, { useEffect, useState } from 'react';
import type { PersonaEntryGuide } from '../PersonaEntrySheet';
interface Props { guide: PersonaEntryGuide; onClose: () => void; onStart: (featureKey?: string) => void; onFeature: (featureKey: string) => void; onInvite: () => void; }
type SampleKey = 'driver' | 'iron' | 'tempo';
type PuttPhase = 'ready' | 'playing' | 'success';
const SAMPLES = {
    driver: { title: '드라이버의 중심을 찾는 스윙', sub: '힘보다 순서가 먼저인 날의 코칭 노트', values: [72, 64, 81, 69, 76], coach: '백스윙을 더 크게 만들기보다, 왼발이 먼저 바닥을 누르는 감각부터 연습해 보세요.' },
    iron: { title: '아이언의 낮은 지점을 앞으로', sub: '정확한 컨택을 위한 세 가지 기준', values: [78, 71, 68, 83, 74], coach: '공을 띄우려 하지 말고 손이 공보다 조금 먼저 지나간다는 느낌을 가져가세요.' },
    tempo: { title: '서두르지 않는 나만의 템포', sub: '백스윙과 전환의 리듬을 맞추는 노트', values: [80, 75, 62, 73, 79], coach: '전환에서 바로 힘을 쓰지 말고 하나를 세고 내려오는 리듬을 만들어 보세요.' },
} as const;
const LABELS = ['어드레스', '백스윙', '다운스윙', '임팩트', '피니시'];
const CSS = `
.sg-root{--night:#071821;--green:#1f5243;--mint:#91c9b0;--gold:#e0bd6d;--paper:#f5f1e8;--wine:#b65f62;--ink:#132b31;position:fixed;inset:0;z-index:85;overflow-y:auto;overflow-x:hidden;background:var(--night);color:#fff;font-family:Pretendard,"Apple SD Gothic Neo","Noto Sans KR",sans-serif}.sg-root *{box-sizing:border-box}.sg-root button{font:inherit;cursor:pointer;touch-action:manipulation}.sg-scene{position:absolute;inset:0;width:100%;height:100%}.sg-scene img{width:100%;height:100%;display:block;object-fit:cover}.sg-hero{min-height:min(900px,100svh);position:relative;display:flex;align-items:flex-end;overflow:hidden;background:#06141d}.sg-hero:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(4,17,24,.88),rgba(4,17,24,.28) 48%,transparent 72%),linear-gradient(0deg,rgba(4,17,24,.86),transparent 50%);pointer-events:none}.sg-top{position:absolute;z-index:4;top:0;left:0;right:0;display:flex;align-items:center;justify-content:space-between;padding:20px clamp(20px,5vw,72px)}.sg-brand{display:flex;align-items:center;gap:10px;font:15px Georgia,"Noto Serif KR",serif;text-shadow:0 2px 10px #000}.sg-mark{width:31px;height:31px;border:1px solid #ffffffaa;border-radius:50%;position:relative}.sg-mark:after{content:'•••';position:absolute;inset:2px 0 0;text-align:center;color:var(--gold);font-size:9px;writing-mode:vertical-rl}.sg-close{width:44px;height:44px;border-radius:50%;border:1px solid #ffffff50;background:#0311189c;color:#fff;font-size:20px}.sg-copy{position:relative;z-index:3;margin:0 0 clamp(30px,5vh,54px) clamp(20px,6vw,86px);width:min(650px,calc(100% - 40px))}.sg-eyebrow,.sg-kicker{font-size:11px;font-weight:800;letter-spacing:.14em}.sg-eyebrow{display:flex;align-items:center;gap:12px;color:#edf4f1}.sg-eyebrow:before{content:'';width:38px;border-top:1px solid var(--gold)}.sg-copy h1{font:500 clamp(39px,5.3vw,68px)/1.04 Georgia,"Noto Serif KR",serif;letter-spacing:-.04em;margin:12px 0}.sg-gold{color:var(--gold)}.sg-lead{max-width:45ch;color:#e1e9e6;font-size:clamp(14px,1.5vw,18px);line-height:1.65;margin:0}.sg-lead strong{color:#fff}.sg-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:19px}.sg-primary,.sg-secondary{min-height:48px;padding:0 19px;border-radius:3px;font-weight:800}.sg-primary{border:0;background:var(--paper);color:var(--ink)}.sg-secondary{border:1px solid #ffffff70;background:#0311189c;color:#fff}.sg-note{margin-top:10px;color:#bfceca;font-size:10px}
.sg-game{position:fixed;inset:0;z-index:10;display:grid;place-items:center;padding:20px;background:rgba(1,9,13,.88);backdrop-filter:blur(12px);animation:sg-game-in .28s ease-out}.sg-game-shell{width:min(1180px,100%);border:1px solid #ffffff35;border-radius:14px;overflow:hidden;background:#06141d;box-shadow:0 34px 100px #000b}.sg-game-hud{height:54px;display:flex;align-items:center;justify-content:space-between;padding:0 18px;color:#dce8e4}.sg-game-hud strong{font:600 15px Georgia,"Noto Serif KR",serif}.sg-game-hud span{color:var(--gold);font-size:11px;font-weight:800;letter-spacing:.14em}.sg-game-stage{position:relative;width:100%;aspect-ratio:1672/936;overflow:hidden}.sg-game-stage .sg-scene{position:absolute}.sg-game-stage:after{content:"";position:absolute;inset:0;box-shadow:inset 0 0 80px #00101880;pointer-events:none}.sg-game-footer{height:58px;display:flex;align-items:center;justify-content:space-between;padding:0 18px;color:#dce8e4;font-size:12px}.sg-game-meter{display:flex;align-items:center;gap:9px}.sg-game-meter i{display:block;width:120px;height:4px;background:linear-gradient(90deg,var(--mint) 70%,#ffffff28 70%);border-radius:3px}.sg-skip{border:1px solid #ffffff65;background:transparent;color:#fff;border-radius:20px;padding:8px 14px;font-size:11px}.sg-sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0)}@keyframes sg-game-in{from{opacity:0;transform:scale(.985)}to{opacity:1;transform:scale(1)}}
.sg-choose{background:var(--paper);color:var(--ink);padding:clamp(64px,9vw,110px) clamp(20px,7vw,104px)}.sg-head{max-width:1180px;margin:auto;display:grid;grid-template-columns:.85fr 1.15fr;gap:52px;align-items:end}.sg-kicker{color:#477060}.sg-head h2,.sg-desk-copy h2{font:500 clamp(34px,4.5vw,56px)/1.2 Georgia,"Noto Serif KR",serif;margin:13px 0 0}.sg-head p,.sg-desk-copy p{color:#586a68;line-height:1.8;font-size:14px}.sg-paths{max-width:1180px;margin:54px auto 0;display:grid;grid-template-columns:1fr 1fr;border-top:1px solid #c9c6ba}.sg-path{padding:34px 38px 28px 0}.sg-path+.sg-path{padding-left:38px;border-left:1px solid #d5d1c5}.sg-num{font:italic 21px Georgia,serif;color:var(--wine)}.sg-path h3{font:600 clamp(24px,3vw,34px) Georgia,"Noto Serif KR",serif;margin:34px 0 12px}.sg-path p{font-size:13px;line-height:1.75;color:#60706e}.sg-chips{display:flex;gap:8px;flex-wrap:wrap;margin:22px 0}.sg-chip{font-size:10px;font-weight:800;padding:7px 9px;border:1px solid #b8c8c0;color:#315c4d;border-radius:20px}.sg-path button{border:0;background:var(--green);color:#fff;padding:13px 17px;border-radius:3px;font-weight:800}.sg-desk{background:#102c2d;padding:clamp(64px,9vw,108px) clamp(20px,7vw,104px)}.sg-desk-inner{max-width:1180px;margin:auto;display:grid;grid-template-columns:.78fr 1.22fr;gap:clamp(40px,8vw,100px)}.sg-desk-copy{position:sticky;top:34px}.sg-desk-copy .sg-kicker{color:var(--mint)}.sg-desk-copy p{color:#b7c9c4}.sg-toggles{display:flex;gap:8px;margin-top:24px}.sg-toggle{border:1px solid #ffffff3d;background:transparent;color:#dce8e4;padding:10px 13px;border-radius:3px}.sg-toggle[aria-pressed=true]{background:var(--mint);border-color:var(--mint);color:#0a2727;font-weight:800}.sg-report{background:var(--paper);color:var(--ink);border-radius:5px;padding:clamp(26px,5vw,52px);box-shadow:0 28px 80px #0005;min-height:520px}.sg-sample{font-size:10px;font-weight:800;color:var(--wine)}.sg-report h3{font:500 clamp(27px,4vw,42px)/1.25 Georgia,"Noto Serif KR",serif;margin:24px 0 6px}.sg-sub{font-size:12px;color:#6d7a77;margin-bottom:30px}.sg-metrics{border-top:1px solid #c9c9bf}.sg-metric{display:grid;grid-template-columns:50px 1fr 120px;gap:15px;align-items:center;padding:17px 0;border-bottom:1px solid #d8d6cc}.sg-metric b{font:italic 17px Georgia,serif;color:var(--wine)}.sg-bar{height:4px;background:#d8d9d1}.sg-bar i{display:block;height:100%;background:var(--green)}.sg-coach{margin-top:28px;padding:19px;border-left:3px solid var(--gold);background:#ebe8df;color:#536461;font-size:12px;line-height:1.75}.sg-disclosure{margin-top:17px;color:#7c8783;font-size:10px;line-height:1.6}.sg-root :focus-visible{outline:3px solid #f3d480;outline-offset:3px}
@media(max-width:760px){.sg-hero{min-height:auto;padding-top:72svh;display:block;background:#071821}.sg-hero .sg-scene{height:72svh}.sg-hero:after{height:72svh;background:linear-gradient(0deg,#071821,transparent 36%)}.sg-top{padding:16px}.sg-brand span:last-child{display:none}.sg-copy{margin:0;padding:18px 20px 30px;width:auto;background:#071821}.sg-copy h1{font-size:39px}.sg-lead{font-size:14px}.sg-actions>*{flex:1 1 100%}.sg-game{padding:10px}.sg-game-shell{width:auto;max-width:100%;border-radius:11px}.sg-game-hud{height:48px}.sg-game-stage{height:min(72svh,680px);width:auto;aspect-ratio:942/1674}.sg-game-footer{height:54px}.sg-game-meter i{width:72px}.sg-head,.sg-desk-inner{grid-template-columns:1fr}.sg-paths{grid-template-columns:1fr}.sg-path,.sg-path+.sg-path{padding:28px 0;border-left:0;border-bottom:1px solid #d5d1c5}.sg-path:last-child{border-bottom:0}.sg-path h3{margin:18px 0 10px}.sg-desk-copy{position:static}.sg-report{min-height:0}.sg-metric{grid-template-columns:42px 1fr}.sg-bar{grid-column:2;width:100%}}
`;
/*
 * v6 퍼팅 스트로크
 * 프레임 4장은 전부 같은 어드레스 원본 한 장을 판으로 쓰고, 팔·손·어깨·퍼터 영역만
 * 갈아끼운 합성본이다. 얼굴·머리·다리·발·배경은 원본 픽셀 그대로라 프레임이 바뀌어도
 * 사람이 이동하거나 다른 사람으로 바뀔 수 없다(v5는 장마다 따로 생성해 사람이 튀었다).
 *
 * 4.8초 한 주기 안의 스트로크 타임라인(리디아고 퍼팅 기본기 기준 — 머리 고정, 손목 고정,
 * 어깨 진자, 손이 헤드보다 앞):
 *   0.00~0.43s 어드레스 / 0.46~0.99s 백스트로크(천천히) / 1.02s 임팩트
 *   1.06~1.18s 임팩트 직후 / 1.21~1.83s 낮은 팔로스루 / 1.87~2.10s 되돌아오는 길
 *   2.13s~ 어드레스 복귀
 * ★레이어 순서는 어드레스 < back < thru < follow. 위 레이어가 사라지기 전에 아래
 *   레이어가 먼저 불투명해지도록 짜서, 교차구간에 상이 세 겹으로 겹치지 않는다.
 *
 * ★공과 홀컵 마커는 그리지 않는다(2026-09-18 사장 지시). 생성 모델이 이 구도에서
 *   퍼터 헤드를 항상 타깃 라인과 나란히 눕혀 그려 페이스가 홀이 아니라 카메라를 본다.
 *   그 상태로 공을 홀까지 굴리면 조준과 궤적이 어긋나 보이므로, 조준을 주장하지 않는
 *   스트로크 동작만 남겼다. 퍼터가 제대로 조준된 소재를 확보하기 전에는 되살리지 말 것.
 */
const MOTION_CSS = `
.sg-stroke{position:absolute;inset:0;opacity:0;animation-duration:4.8s;animation-timing-function:linear;animation-fill-mode:forwards}.sg-stroke-back{animation-name:sg-stroke-back}.sg-stroke-thru{animation-name:sg-stroke-thru}.sg-stroke-follow{animation-name:sg-stroke-follow}
@keyframes sg-stroke-back{0%,8.9%{opacity:0}9.6%,20.6%{opacity:1}21.3%,100%{opacity:0}}
@keyframes sg-stroke-thru{0%,21.3%{opacity:0}22%,25.3%{opacity:1}26%,37.2%{opacity:0}37.9%,43.7%{opacity:1}44.4%,100%{opacity:0}}
@keyframes sg-stroke-follow{0%,24.6%{opacity:0}25.3%,38.2%{opacity:1}38.9%,100%{opacity:0}}
@media(prefers-reduced-motion:reduce){.sg-stroke{animation-duration:.01ms}.sg-root{scroll-behavior:auto}}
`;
const ResponsiveScene: React.FC<{ mobile: string; desktop: string; alt: string }> = ({ mobile, desktop, alt }) => <picture className="sg-scene"><source media="(max-width: 760px)" srcSet={mobile} /><img src={desktop} alt={alt} /></picture>;
export const SeolaGolfEntry: React.FC<Props> = ({ guide, onClose, onStart, onFeature }) => {
    const [sampleKey, setSampleKey] = useState<SampleKey>('driver');
    const [puttPhase, setPuttPhase] = useState<PuttPhase>('ready');
    const sample = SAMPLES[sampleKey];
    useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', onKeyDown); return () => window.removeEventListener('keydown', onKeyDown); }, [onClose]);
    useEffect(() => {
        if (window.matchMedia?.('(prefers-reduced-motion: reduce)').matches) { setPuttPhase('success'); return; }
        const start = window.setTimeout(() => setPuttPhase('playing'), 900);
        return () => window.clearTimeout(start);
    }, []);
    useEffect(() => {
        if (puttPhase !== 'playing') return;
        const finish = window.setTimeout(() => setPuttPhase('success'), 5200);
        return () => window.clearTimeout(finish);
    }, [puttPhase]);
    return <div className="sg-root" role="dialog" aria-modal="true" aria-label={`${guide.title} 골프 코칭`}><style>{CSS + MOTION_CSS}</style>
        <section className="sg-hero" aria-labelledby="seola-title"><ResponsiveScene mobile={puttPhase === 'success' ? '/seola/celebrate-mobile-v3.png' : '/seola/putt-address-mobile-v6.webp'} desktop={puttPhase === 'success' ? '/seola/celebrate-desktop-v3.png' : '/seola/putt-address-desktop-v6.webp'} alt={puttPhase === 'success' ? '퍼팅에 성공해 기뻐하는 설아' : '정석 어드레스로 퍼팅을 준비하는 설아'} /><header className="sg-top"><div className="sg-brand"><span className="sg-mark" aria-hidden="true" /><span>설아의 새벽 티하우스</span></div><button className="sg-close" type="button" aria-label="닫기" onClick={onClose}>×</button></header><div className="sg-copy"><div className="sg-eyebrow">AI GOLF COACH · COURSE GUIDE</div><h1 id="seola-title">감이 아니라,<br /><span className="sg-gold">나의 리듬으로</span></h1><p className="sg-lead">스윙 영상 한 번이면 충분해요. <strong>설아 코치</strong>가 움직임을 차분히 읽고, 오늘의 코스까지 함께 준비합니다.</p><div className="sg-actions"><button className="sg-primary" type="button" onClick={() => onFeature('swing')}>내 스윙 점검하기</button><button className="sg-secondary" type="button" onClick={() => onFeature('golf-course')}>오늘의 코스 찾기</button><button className="sg-secondary" type="button" onClick={() => onStart()}>설아와 대화하기</button></div><div className="sg-note">분석은 영상을 올리고 시작을 선택한 뒤에만 진행됩니다.</div></div></section>
        {puttPhase === 'playing' && <div className="sg-game" role="dialog" aria-modal="true" aria-label="설아의 퍼팅 게임"><div className="sg-game-shell"><div className="sg-game-hud"><strong>설아의 퍼팅 라인</strong><span>PUTT · 2.8 M</span></div><div className="sg-game-stage"><ResponsiveScene mobile="/seola/putt-address-mobile-v6.webp" desktop="/seola/putt-address-desktop-v6.webp" alt="홀을 향해 어드레스를 잡은 설아" /><picture className="sg-scene sg-stroke sg-stroke-back"><source media="(max-width: 760px)" srcSet="/seola/putt-back-mobile-v6.webp" /><img src="/seola/putt-back-desktop-v6.webp" alt="어깨를 함께 돌려 퍼터를 낮게 뒤로 빼는 설아" /></picture><picture className="sg-scene sg-stroke sg-stroke-thru"><source media="(max-width: 760px)" srcSet="/seola/putt-thru-mobile-v6.webp" /><img src="/seola/putt-thru-desktop-v6.webp" alt="손이 헤드보다 앞선 채 공을 지나가는 설아" /></picture><picture className="sg-scene sg-stroke sg-stroke-follow"><source media="(max-width: 760px)" srcSet="/seola/putt-follow-mobile-v6.webp" /><img src="/seola/putt-follow-desktop-v6.webp" alt="퍼터를 낮게 홀 쪽으로 밀어내는 설아" /></picture></div><div className="sg-game-footer"><div className="sg-game-meter"><span>거리감</span><i aria-hidden="true" /><strong>좋음</strong></div><button className="sg-skip" type="button" onClick={() => setPuttPhase('success')}>건너뛰기</button></div></div><div className="sg-sr" aria-live="polite">머리는 고정한 채 어깨와 팔이 함께 뒤로 갔다가, 손이 헤드보다 앞선 상태로 퍼터가 낮게 지나가며 퍼팅 스트로크를 마칩니다.</div></div>}
        <section className="sg-choose" aria-labelledby="seola-path-title"><div className="sg-head"><div><div className="sg-kicker">CHOOSE YOUR ROUND</div><h2 id="seola-path-title">연습도 라운드도,<br />한 흐름으로</h2></div><p>좋은 라운드는 내 움직임을 이해하는 데서 시작합니다. 먼저 스윙을 점검해도 좋고, 오늘 갈 코스를 찾아도 괜찮습니다.</p></div><div className="sg-paths"><article className="sg-path"><div className="sg-num">01</div><h3>스윙 분석</h3><p>영상을 올리면 어드레스부터 피니시까지 다섯 구간을 나눠 보고, 지금 고칠 한 가지를 먼저 짚습니다.</p><div className="sg-chips"><span className="sg-chip">영상 업로드</span><span className="sg-chip">5구간 점검</span><span className="sg-chip">연습 포인트</span></div><button type="button" onClick={() => onFeature('swing')}>스윙 분석 시작 →</button></article><article className="sg-path"><div className="sg-num">02</div><h3>내 주변 골프장</h3><p>현재 위치나 지역으로 실제 골프장을 찾고, 확인 가능한 정보 안에서 코스 특징과 공략 포인트를 브리핑합니다.</p><div className="sg-chips"><span className="sg-chip">거리순 탐색</span><span className="sg-chip">코스 브리핑</span><span className="sg-chip">후기·예약처 연결</span></div><button type="button" onClick={() => onFeature('golf-course')}>코스 찾아보기 →</button></article></div></section>
        <section className="sg-desk" aria-labelledby="seola-note-title"><div className="sg-desk-inner"><div className="sg-desk-copy"><div className="sg-kicker">[예시] COACHING NOTE</div><h2 id="seola-note-title">설아는 이렇게<br />읽어드려요</h2><p>분석 결과가 어떤 형태로 정리되는지 먼저 살펴보세요. 아래 수치와 문구는 화면 구성을 위한 예시입니다.</p><div className="sg-toggles" role="group" aria-label="예시 스윙 선택">{([['driver','드라이버'],['iron','아이언'],['tempo','템포']] as [SampleKey,string][]).map(([key,label]) => <button key={key} className="sg-toggle" type="button" aria-pressed={sampleKey===key} onClick={() => setSampleKey(key)}>{label}</button>)}</div></div><article className="sg-report" aria-live="polite"><div className="sg-sample">[예시] SWING REVIEW</div><h3>{sample.title}</h3><div className="sg-sub">{sample.sub}</div><div className="sg-metrics">{LABELS.map((label,index)=><div className="sg-metric" key={label}><b>0{index+1}</b><strong>{label}</strong><span className="sg-bar" aria-label={`예시 ${label} ${sample.values[index]}`}><i style={{width:`${sample.values[index]}%`}} /></span></div>)}</div><div className="sg-coach">“{sample.coach}”</div><div className="sg-disclosure">이 내용은 화면 구성을 보여주기 위한 예시이며 실제 영상 분석 결과가 아닙니다. 사용자의 영상은 명시적인 분석 시작 전에는 처리되지 않습니다.</div></article></div></section>
    </div>;
};
