import React, { useCallback, useEffect, useState } from 'react';
import { adminApi, type DevProjectArtifacts, type DevProjectDetail, type DevProjectRow } from '../../services/apiService';
import { Icon } from '../Icons';

const STATUS:Record<string,string>={draft:'작성중',queued:'대기',planned:'계획됨',awaiting_approval:'승인대기',running:'개발중',review:'검토중',done:'완료',failed:'실패',canceled:'취소'};
const fmt=(value:string)=>{try{return new Date(value).toLocaleString('ko-KR');}catch{return value;}};

export const HerdrResultsPanel:React.FC=()=>{
    const [rows,setRows]=useState<DevProjectRow[]>([]),[selected,setSelected]=useState<DevProjectDetail|null>(null);
    const [artifacts,setArtifacts]=useState<DevProjectArtifacts|null>(null),[busy,setBusy]=useState(true);
    const [error,setError]=useState(''),[artifactWarning,setArtifactWarning]=useState(''),[openReview,setOpenReview]=useState<string|null>(null);
    const load=useCallback(async()=>{try{setBusy(true);setError('');const d=await adminApi.listDevProjects();setRows(d.projects);}catch(e:any){setError(e?.message||'결과 목록을 불러오지 못했습니다.');}finally{setBusy(false);}},[]);
    useEffect(()=>{void load();},[load]);
    const open=async(id:string)=>{try{setBusy(true);setError('');setArtifactWarning('');setArtifacts(null);setOpenReview(null);const detail=await adminApi.getDevProject(id);setSelected(detail.project);try{const files=await adminApi.getDevProjectArtifacts(id);setArtifacts(files.artifacts);}catch(e:any){setArtifactWarning(e?.message||'파일 산출물은 현재 불러오지 못했습니다. 진행 기록은 계속 볼 수 있습니다.');}}catch(e:any){setError(e?.message||'결과 상세를 불러오지 못했습니다.');}finally{setBusy(false);}};
    const download=async()=>{if(!artifacts?.siteSlug)return;try{setBusy(true);await adminApi.downloadSite(artifacts.siteSlug);}catch(e:any){setError(e?.message||'소스 다운로드에 실패했습니다.');}finally{setBusy(false);}};
    const events=selected?.events??[], result=selected?.result;
    return <div className="flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-6xl space-y-4">
        <div className="flex items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-lg font-bold text-white"><Icon name="CheckCircle" size={18} className="text-emerald-400"/>허드 결과</h2><p className="mt-1 text-xs text-gray-400">프로젝트 진행 기록과 산출물을 한 곳에서 확인합니다.</p></div><button onClick={()=>void load()} className="rounded-lg border border-gray-700 px-3 py-2 text-xs text-gray-300 hover:bg-gray-800">새로고침</button></div>
        {error&&<div className="rounded-lg border border-red-800 bg-red-900/30 px-3 py-2 text-xs text-red-300">{error}</div>}
        {artifactWarning&&<div className="rounded-lg border border-amber-800 bg-amber-900/30 px-3 py-2 text-xs text-amber-300">{artifactWarning}</div>}
        <div className="grid gap-4 lg:grid-cols-[280px_1fr]"><aside className="rounded-xl border border-gray-800 bg-gray-900/60 p-3"><div className="mb-2 text-[11px] text-gray-500">프로젝트 {rows.length}건</div><div className="max-h-[70vh] space-y-1.5 overflow-y-auto">{rows.length===0&&!busy&&<p className="py-8 text-center text-xs text-gray-600">아직 결과가 없습니다.</p>}{rows.map(row=><button key={row.id} onClick={()=>void open(row.id)} className={`w-full rounded-lg border px-3 py-2 text-left ${selected?.id===row.id?'border-blue-600 bg-blue-900/30':'border-gray-800 bg-gray-950/50 hover:border-gray-600'}`}><div className="flex gap-2"><span className="min-w-0 flex-1 truncate text-xs text-gray-200">{row.title}</span><span className="shrink-0 text-[10px] text-gray-500">{STATUS[row.status]??row.status}</span></div><div className="mt-1 text-[10px] text-gray-600">{fmt(row.updatedAt)}</div></button>)}</div></aside>
        <main className="min-w-0 space-y-4">{!selected?<div className="rounded-xl border border-gray-800 bg-gray-900/60 py-20 text-center text-xs text-gray-600">왼쪽에서 프로젝트를 선택하세요.</div>:<>
            <section className="rounded-xl border border-gray-800 bg-gray-900/60 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-base font-bold text-white">{selected.title}</h3><p className="mt-1 text-xs text-gray-500">{STATUS[selected.status]??selected.status} · 허드 {selected.herdrProjectId??'미연결'}</p></div><div className="flex flex-wrap gap-2">{result?.deployUrl&&<a href={result.deployUrl} target="_blank" rel="noreferrer" className="rounded-lg bg-blue-600 px-3 py-2 text-xs font-bold text-white">미리보기 열기</a>}<button onClick={()=>void download()} disabled={!artifacts?.sourceAvailable||busy} className="rounded-lg border border-gray-700 px-3 py-2 text-xs font-bold text-gray-300 disabled:opacity-35">소스 ZIP</button></div></div>{result?.summary&&<p className="mt-3 whitespace-pre-wrap text-xs leading-relaxed text-gray-300">{result.summary}</p>}</section>
            <section className="rounded-xl border border-gray-800 bg-gray-900/60 p-4"><h3 className="text-sm font-bold text-white">진행 이벤트 ({events.length})</h3><div className="mt-3 max-h-72 space-y-2 overflow-y-auto">{events.length===0?<p className="text-xs text-gray-600">기록된 이벤트가 없습니다.</p>:events.map(e=><div key={e.id} className="grid grid-cols-[76px_1fr] gap-2 border-b border-gray-800 pb-2 text-xs"><span className="text-gray-500">{e.actor} · {e.phase}</span><div><p className="text-gray-300">{e.message}</p><p className="mt-0.5 text-[10px] text-gray-600">{fmt(e.at)}</p></div></div>)}</div></section>
            <section className="rounded-xl border border-gray-800 bg-gray-900/60 p-4"><h3 className="text-sm font-bold text-white">결과 이미지 ({artifacts?.images.length??0})</h3>{artifacts?.images.length?<div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-3 xl:grid-cols-4">{artifacts.images.map(img=><a key={img.url} href={img.url} target="_blank" rel="noreferrer" className="overflow-hidden rounded-lg border border-gray-800 bg-gray-950"><img src={img.url} alt={img.name} loading="lazy" className="h-28 w-full object-cover"/><div className="truncate px-2 py-1.5 text-[10px] text-gray-500">{img.name}</div></a>)}</div>:<p className="mt-3 text-xs text-gray-600">표시할 결과 이미지가 없습니다.</p>}{artifacts?.imagesTruncated&&<p className="mt-2 text-xs text-amber-300">이미지가 많아 최근 표시 한도까지만 보여줍니다.</p>}</section>
            <section className="rounded-xl border border-gray-800 bg-gray-900/60 p-4"><h3 className="text-sm font-bold text-white">사양서</h3>{artifacts?.spec?<><pre className="mt-3 max-h-96 overflow-auto whitespace-pre-wrap rounded-lg bg-gray-950 p-3 text-xs leading-relaxed text-gray-300">{artifacts.spec.text}</pre>{artifacts.spec.truncated&&<p className="mt-2 text-xs text-amber-300">화면 표시 한도로 일부만 보여줍니다. ZIP에서 전체 파일을 확인하세요.</p>}</>:<p className="mt-3 text-xs text-gray-600">SPEC.md가 없습니다.</p>}</section>
            <section className="rounded-xl border border-gray-800 bg-gray-900/60 p-4"><h3 className="text-sm font-bold text-white">Reviewer 기록 ({artifacts?.reviews.length??0})</h3><div className="mt-3 space-y-2">{artifacts?.reviews.length?artifacts.reviews.map(r=><div key={`${r.date}/${r.fileName}`} className="rounded-lg border border-gray-800"><button onClick={()=>setOpenReview(v=>v===r.fileName?null:r.fileName)} className="flex w-full items-center justify-between gap-2 px-3 py-2 text-left"><span className="truncate text-xs text-gray-300">{r.date} · {r.fileName}</span><span className="text-[10px] text-gray-600">{openReview===r.fileName?'접기':'보기'}</span></button>{openReview===r.fileName&&<pre className="max-h-96 overflow-auto whitespace-pre-wrap border-t border-gray-800 bg-gray-950 p-3 text-xs leading-relaxed text-gray-300">{r.text}</pre>}</div>):<p className="text-xs text-gray-600">보관된 Reviewer 기록이 없습니다.</p>}</div></section>
        </>}</main></div>{busy&&<div role="status" className="text-center text-xs text-gray-500">불러오는 중…</div>}
    </div></div>;
};
