import React, { useEffect, useMemo, useState } from 'react';
import { adminApi } from '../../services/apiService';
import { Icon } from '../Icons';
import { EMPTY_SHORTS_HERDR_BRIEF, EMPTY_VIDEO_HERDR_BRIEF, buildShortsHerdrHandoff, buildVideoHerdrHandoff, isShortsHerdrBriefReady, isVideoHerdrBriefReady, type ShortsHerdrBrief, type VideoHerdrBrief } from './herdrTaskBrief';

const cls='w-full rounded-lg border border-gray-700 bg-gray-950/70 px-3 py-2.5 text-sm text-white placeholder:text-gray-600 focus:border-blue-500 focus:outline-none';
const Label:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><label className="block space-y-1.5"><span className="text-xs font-bold text-gray-300">{title}</span>{children}</label>;

export const MediaHerdrPanel:React.FC<{kind:'shorts'|'video'}>=({kind})=>{
    const [shorts,setShorts]=useState<ShortsHerdrBrief>(EMPTY_SHORTS_HERDR_BRIEF);
    const [video,setVideo]=useState<VideoHerdrBrief>(EMPTY_VIDEO_HERDR_BRIEF);
    const [review,setReview]=useState(true),[saved,setSaved]=useState<{id:string;signature:string}|null>(null);
    const [concurrency,setConcurrency]=useState({running:0,max:1,canStart:true});
    const [busy,setBusy]=useState(false),[msg,setMsg]=useState(''),[err,setErr]=useState('');
    const isShorts=kind==='shorts';
    const handoff=useMemo(()=>isShorts?buildShortsHerdrHandoff(shorts):buildVideoHerdrHandoff(video),[isShorts,shorts,video]);
    const ready=isShorts?isShortsHerdrBriefReady(shorts):isVideoHerdrBriefReady(video);
    const signature=`${handoff}\nreview=${review}`, dirty=saved?.signature!==signature;
    useEffect(()=>{adminApi.listDevProjects().then(d=>setConcurrency(d.concurrency)).catch(()=>{});},[]);
    useEffect(()=>{setSaved(null);setMsg('');setErr('');},[kind]);
    const title=isShorts?'쇼츠 만들기':'영상 만들기 (i2v)';
    const projectName=isShorts?shorts.projectName:video.projectName;
    const save=async()=>{if(!ready){setErr('필수 입력을 먼저 채워 주세요.');return;}try{setBusy(true);setErr('');const body={title:`[${isShorts?'쇼츠':'영상'}] ${projectName.trim()}`,features:title,specBody:handoff,refUrls:'',note:`허드 AI ${isShorts?'쇼츠':'영상'} 탭에서 저장`,brief:'{}',useReview:review,workdir:isShorts?'/home/paks11299958/shorts-factory':'/home/paks11299958/ai_mp'};if(saved){await adminApi.updateDevProject({...body,id:saved.id});setSaved({id:saved.id,signature});}else{const d=await adminApi.createDevProject(body);setSaved({id:d.project.id,signature});}setMsg('명세를 저장했습니다. 내용을 확인한 뒤 시작하세요.');}catch(e:any){setErr(e?.message||'명세 저장 실패');}finally{setBusy(false);}};
    const start=async()=>{if(!saved||dirty){setErr('현재 입력을 먼저 저장해 주세요.');return;}if(!concurrency.canStart){setErr('다른 허드 작업이 실행 중입니다.');return;}if(!window.confirm(`'${projectName}' ${isShorts?'쇼츠':'영상'} 제작을 시작할까요?\n외부 발행·배포는 자동으로 하지 않습니다.`))return;try{setBusy(true);setErr('');const d=await adminApi.startDevProject(saved.id);setConcurrency(v=>({...v,running:v.running+1,canStart:false}));setMsg(d.message);}catch(e:any){setErr(e?.message||'허드 시작 실패');}finally{setBusy(false);}};
    const changeShorts=(k:keyof ShortsHerdrBrief,v:string)=>{setShorts(x=>({...x,[k]:v}));setMsg('');};
    const changeVideo=(k:keyof VideoHerdrBrief,v:string)=>{setVideo(x=>({...x,[k]:v}));setMsg('');};
    return <div className="flex-1 overflow-y-auto p-4 sm:p-6"><div className="mx-auto max-w-4xl space-y-5">
        <div><div className="flex items-center gap-2"><Icon name={isShorts?'Play':'Sparkles'} size={18} className="text-blue-400"/><h2 className="text-lg font-bold text-white">{title}</h2><span className="rounded-full bg-green-500/15 px-2 py-1 text-[10px] font-bold text-green-300">허드 연결됨</span></div><p className="mt-1 text-xs text-gray-400">입력과 명세 저장만으로는 실행되지 않습니다. 마지막 시작 버튼과 확인창을 거쳐야 합니다.</p></div>
        {err&&<div className="rounded-lg border border-red-800 bg-red-900/30 px-3 py-2 text-xs text-red-300">{err}</div>}{msg&&<div className="rounded-lg border border-emerald-800 bg-emerald-900/30 px-3 py-2 text-xs text-emerald-300">{msg}</div>}
        <div className="grid gap-5 lg:grid-cols-2"><section className="space-y-4 rounded-2xl border border-gray-800 bg-gray-900/70 p-5">
        {isShorts?<><Label title="프로젝트명 *"><input className={cls} value={shorts.projectName} onChange={e=>changeShorts('projectName',e.target.value)}/></Label><Label title="소재 *"><textarea className={cls} rows={3} value={shorts.topic} onChange={e=>changeShorts('topic',e.target.value)}/></Label><Label title="대본 방식"><select className={cls} value={shorts.scriptMode} onChange={e=>changeShorts('scriptMode',e.target.value)}><option value="ai">AI가 초안 작성</option><option value="direct">직접 입력</option></select></Label>{shorts.scriptMode==='direct'&&<Label title="대본 *"><textarea className={cls} rows={5} value={shorts.script} onChange={e=>changeShorts('script',e.target.value)}/></Label>}<div className="grid grid-cols-2 gap-3"><Label title="장면 수 *"><input className={cls} type="number" min="1" max="20" value={shorts.sceneCount} onChange={e=>changeShorts('sceneCount',e.target.value)}/></Label><Label title="화자 *"><input className={cls} value={shorts.narrator} onChange={e=>changeShorts('narrator',e.target.value)} placeholder="예: Leda"/></Label></div><Label title="이미지 생성기"><select className={cls} value={shorts.imageGenerator} onChange={e=>changeShorts('imageGenerator',e.target.value)}><option value="z-image">Z-Image</option><option value="gemini">Gemini</option></select></Label><Label title="수정 금지 파일·경로"><input className={cls} value={shorts.forbiddenFiles} onChange={e=>changeShorts('forbiddenFiles',e.target.value)}/></Label></>:<><Label title="프로젝트명 *"><input className={cls} value={video.projectName} onChange={e=>changeVideo('projectName',e.target.value)}/></Label><Label title="원본 이미지 경로 *"><input className={cls} value={video.sourceImage} onChange={e=>changeVideo('sourceImage',e.target.value)} placeholder="서버2의 기존 이미지 경로"/></Label><Label title="사용 목적 *"><textarea className={cls} rows={3} value={video.purpose} onChange={e=>changeVideo('purpose',e.target.value)}/></Label><div className="grid grid-cols-2 gap-3"><Label title="움직임"><select className={cls} value={video.motion} onChange={e=>changeVideo('motion',e.target.value)}><option value="slow_push_in">천천히 접근</option><option value="slow_pull_out">천천히 멀어짐</option><option value="pan_left">왼쪽 이동</option><option value="pan_right">오른쪽 이동</option></select></Label><Label title="길이(초)"><input className={cls} type="number" step="0.125" min="1" value={video.duration} onChange={e=>changeVideo('duration',e.target.value)}/></Label></div><Label title="수정 금지 파일·경로"><input className={cls} value={video.forbiddenFiles} onChange={e=>changeVideo('forbiddenFiles',e.target.value)}/></Label><div className="rounded-xl border border-amber-700/40 bg-amber-500/10 p-3 text-xs text-amber-200">Wan i2v는 편당 약 250~566원입니다. 허드 시작 뒤에도 실제 GPU 생성 전에 비용 확인을 요구합니다.</div></>}
        </section><section className="space-y-4 rounded-2xl border border-gray-800 bg-gray-900/70 p-5"><div className="flex items-center justify-between"><div><h3 className="text-sm font-bold text-white">실제 전달 명세</h3><p className="mt-1 text-xs text-gray-500">기존 제작 파이프라인을 재사용하도록 고정했습니다.</p></div><button role="switch" aria-checked={review} onClick={()=>setReview(v=>!v)} className={`rounded-full px-3 py-2 text-xs font-bold ${review?'bg-blue-600 text-white':'bg-gray-800 text-gray-400'}`}>리뷰 {review?'ON':'OFF'}</button></div><pre className="max-h-[30rem] overflow-auto whitespace-pre-wrap rounded-xl bg-gray-950/70 p-4 text-xs leading-relaxed text-gray-300">{handoff}</pre><p className="text-[11px] text-gray-500">예상 20~35분 · 리뷰 시 약 2배 · 동시 실행 {concurrency.running}/{concurrency.max}</p><div className="grid gap-2"><button onClick={save} disabled={!ready||busy} className="rounded-xl border border-blue-500/50 bg-blue-500/10 px-4 py-3 text-sm font-bold text-blue-200 disabled:opacity-35">{saved&&!dirty?'✓ 명세 저장됨':saved?'변경 명세 저장':'1. 명세 저장'}</button><button onClick={start} disabled={!saved||dirty||busy||!concurrency.canStart} className="rounded-xl bg-blue-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-35">2. 허드 시작</button></div><p className="text-[11px] text-gray-500">자동 업로드·외부 발행·운영 배포는 하지 않습니다.</p></section></div>
    </div></div>;
};
